name: Manage GitHub Branches

on:
  workflow_dispatch:

jobs:
  manage-branches:
    runs-on: ubuntu-latest

    steps:
    - name: List Branches
      run: |
        curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/Morethanatester/django-benpavey/branches

    - name: Delete Branch feature/add-about-page
      run: |
        curl -X DELETE -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/Morethanatester/django-benpavey/git/refs/heads/feature/add-about-page

    - name: Delete Branch release-v1.0.0
      run: |
        curl -X DELETE -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/Morethanatester/django-benpavey/git/refs/heads/release-v1.0.0

    - name: Delete Branch release-v1.1.0
      run: |
        curl -X DELETE -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/Morethanatester/django-benpavey/git/refs/heads/release-v1.1.0