name: "CD Production Pipeline"

# This CD workflow triggers on manual workflow dispatch.

on:
    workflow_dispatch:
  
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.8'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt



    # Job to deploy to production environment
    deploy-prod:
        runs-on: ubuntu-latest
        needs: build
        if: ${{ github.ref == 'refs/heads/main' || (github.event_name == 'pull_request' && github.base_ref == 'main') }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            # Skeleton step for downloading test results
            # Uncomment and configure the following steps if you want to download test results as artifacts
            # - name: Download test results
            #   uses: actions/download-artifact@v3
            #   with:
            #     name: test-results
            #     path: core/tests/test-results

            # Deploy via Render Deploy Hook
            - name: Trigger Render Deploy Hook (Production)
              env:
                RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_PROD_DEPLOY_HOOK_URL }}  # Use GitHub Secrets for secure deploy hook URL management
              run: |
                curl -X POST $RENDER_DEPLOY_HOOK_URL