name: CI Workflow

on:
  push:
    branches:
      - dev
      - pre-prod
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test core.tests

  promote_to_preprod:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Promote to Pre-prod Environment
        run: |
          echo "Promoting to Pre-prod environment..."

  promote_to_main:
    runs-on: ubuntu-latest
    needs: promote_to_preprod
    if: github.ref == 'refs/heads/pre-prod'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Promote to Production Environment
        run: |
          echo "Promoting to Production environment..."