name: CI/CD Pipeline

on:
  push:
    branches:
      - 'feature/*'
      - 'dev'
      - 'pre-prod'
      - 'main'
  pull_request:
    branches:
      - 'feature/*'
      - 'dev'
      - 'pre-prod'
      - 'main'

jobs:
  # Job to run tests on feature branches
  test:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/feature/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python manage.py test core.tests

  # Promote feature branch to dev
  promote_to_dev:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/heads/feature/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make promote.sh executable
        run: chmod +x tools/promote.sh

      - name: Promote feature to Dev
        run: tools/promote.sh feature-to-dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_EMAIL: ${{ secrets.GH_EMAIL }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}

  # Promote dev to pre-prod
  promote_to_preprod:
    runs-on: ubuntu-latest
    needs: promote_to_dev
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make promote.sh executable
        run: chmod +x tools/promote.sh

      - name: Promote to Pre-Prod
        run: tools/promote.sh pre-prod
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_EMAIL: ${{ secrets.GH_EMAIL }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}

  # Promote pre-prod to main
  promote_to_main:
    runs-on: ubuntu-latest
    needs: promote_to_preprod
    if: github.ref == 'refs/heads/pre-prod'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make promote.sh executable
        run: chmod +x tools/promote.sh

      - name: Promote to Main
        run: tools/promote.sh main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_EMAIL: ${{ secrets.GH_EMAIL }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}

  # Sync dev with main after promotion cycle
  sync_dev_with_main:
    runs-on: ubuntu-latest
    needs: promote_to_main
    if: github.ref == 'refs/heads/main'  # Only runs when changes are promoted to main
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Rebase dev onto main
        run: |
          git fetch origin
          git checkout dev
          git rebase origin/main  # Rebase dev onto main
          git push origin dev --force-with-lease  # Push rebase changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
