name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  # Job to run tests
  test:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: 'True'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python manage.py test core.tests

  # Job to deploy to development environment
  deploy-dev:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/development'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Deploy via Render Deploy Hook
      - name: Trigger Render Deploy Hook (Development)
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEV_DEPLOY_HOOK_URL }}  # Use GitHub Secrets for secure deploy hook URL management
        run: |
          # Trigger deployment via Render Deploy Hook
          curl -X POST $RENDER_DEPLOY_HOOK_URL

  # Job to deploy to production environment
  deploy-prod:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Deploy via Render Deploy Hook
      - name: Trigger Render Deploy Hook (Production)
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_PROD_DEPLOY_HOOK_URL }}  # Use GitHub Secrets for secure deploy hook URL management
        run: |
          # Trigger deployment via Render Deploy Hook
          curl -X POST $RENDER_DEPLOY_HOOK_URL