name: CI/CD Pipeline

on:
  push:
    branches:
      - 'feature/*'     # Runs on any feature branch
      - 'dev'           # Runs on dev branch
      - 'pre-prod'      # Runs on pre-prod branch
      - 'main'          # Runs on main branch
  pull_request:
    branches:
      - 'feature/*'     # Runs on pull requests to any feature branch
      - 'dev'           # Runs on pull requests to dev
      - 'pre-prod'      # Runs on pull requests to pre-prod
      - 'main'          # Runs on pull requests to main

jobs:
  test:
    # Run tests on feature branches to validate code before promotion
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/feature/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python manage.py test core.tests

  promote_to_dev:
    # Promote a successful feature branch to dev
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/heads/feature/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make promote.sh executable
        run: chmod +x tools/promote.sh

      - name: Promote feature to Dev
        run: tools/promote.sh feature-to-dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_EMAIL: ${{ secrets.GH_EMAIL }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}

  promote_to_preprod:
    # Promote dev to pre-prod after dev branch is updated
    runs-on: ubuntu-latest
    needs: promote_to_dev
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make promote.sh executable
        run: chmod +x tools/promote.sh

      - name: Promote to Pre-Prod
        run: tools/promote.sh pre-prod
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_EMAIL: ${{ secrets.GH_EMAIL }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}

  promote_to_main:
    # Promote pre-prod to main for final production deployment
    runs-on: ubuntu-latest
    needs: promote_to_preprod
    if: github.ref == 'refs/heads/pre-prod'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make promote.sh executable
        run: chmod +x tools/promote.sh

      - name: Promote to Main
        run: tools/promote.sh main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_EMAIL: ${{ secrets.GH_EMAIL }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
