name: CD Production Pipeline

# Summary:
# This workflow is triggered on push to the main branch.
# It consists of two jobs:
# 1. Build:
#    - Checks out the code.
#    - Sets up Python 3.8.
#    - Installs dependencies.
# 2. Deploy to Production:
#    - Runs only if the build job succeeds.
#    - Checks out the code.
#    - Optionally downloads test results.
#    - Triggers a deployment via a Render Deploy Hook using a secure URL stored in GitHub Secrets.

on:
  push:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  # Job to deploy to production environment
  deploy-prod:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Skeleton step for downloading test results
      # Uncomment and configure the following steps if you want to download test results as artifacts
      # - name: Download test results
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: test-results
      #     path: core/tests/test-results

      # Deploy via Render Deploy Hook
      - name: Trigger Render Deploy Hook (Production)
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_PROD_DEPLOY_HOOK_URL }}  # Use GitHub Secrets for secure deploy hook URL management
        run: |
          curl -X POST $RENDER_DEPLOY_HOOK_URL || exit 1