name: Django CI

on:
  push:
    branches: [ "main", "pre-prod", "dev" ]
  pull_request:
    branches: [ "main", "pre-prod", "dev" ]

jobs:
  build:
    name: Run Django Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all branches and full history
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test core.tests

  push-to-pre-prod:
    name: Push to Pre-Prod
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/dev' && success() }}
    steps:
    - name: Check out the code
      uses: actions/checkout@v4
    - name: Set up Git
      run: |
        git config --global user.name '${{ secrets.GH_USERNAME }}'
        git config --global user.email '${{ secrets.GH_EMAIL }}'
    - name: Push to Pre-Prod
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        git fetch origin +refs/heads/*:refs/remotes/origin/*
        git checkout pre-prod || git checkout -b pre-prod origin/pre-prod
        git merge dev --no-ff --allow-unrelated-histories -m "Merge from dev to pre-prod"
        git push https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }} pre-prod

  push-to-main:
    name: Push to Main
    runs-on: ubuntu-latest
    needs: push-to-pre-prod
    if: ${{ github.ref == 'refs/heads/dev' && success() }}
    steps:
    - name: Fetch All Remote Branches
      run: git fetch origin +refs/heads/*:refs/remotes/origin/*
    - name: Check out Main Branch
      run: git checkout main || git checkout -b main origin/main
    - name: Set up Git
      run: |
        git config --global user.name '${{ secrets.GH_USERNAME }}'
        git config --global user.email '${{ secrets.GH_EMAIL }}'
    - name: Push to Main
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        git merge pre-prod --no-ff --allow-unrelated-histories -m "Merge from pre-prod to main"
        git push https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }} main
