name: Django CI

on:
  push:
    branches: [ "main", "pre-prod" , "dev" ]
  pull_request:
    branches: [ "main"]

jobs:
  build:
    name: Run Django Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test core.tests