name: Django CI

on:
  push:
    branches: [ "main", "pre-prod", "dev" ]
  pull_request:
    branches: [ "main", "pre-prod", "dev" ]

jobs:
  build:
    name: Run Django Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test core.tests

  push-to-pre-prod:
    name: Push to Pre-Prod
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/dev' && success()
    steps:
    - name: Check out the code
      uses: actions/checkout@v4
    - name: Set up Git
      run: |
        git config --global user.name '${{ secrets.GH_USERNAME }}'
        git config --global user.email '${{ secrets.GH_EMAIL }}'
    - name: Push to Pre-Prod
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        git checkout -b pre-prod
        git push https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }} pre-prod --force

  push-to-main:
    name: Push to Main
    runs-on: ubuntu-latest
    needs: push-to-pre-prod
    if: github.ref == 'refs/heads/dev' && success()
    steps:
    - name: Check out the code
      uses: actions/checkout@v4
    - name: Set up Git
      run: |
        git config --global user.name '${{ secrets.GH_USERNAME }}'
        git config --global user.email '${{ secrets.GH_EMAIL }}'
    - name: Push to Main
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        git checkout main
        git merge pre-prod
        git push https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }} main