name: Deploy and Create PR

on:
  workflow_run:
    workflows: ["Test and Lint", "Django CI"]
    types:
      - completed
      

jobs:
  deploy-and-pr:
    name: Deploy and Create PR
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python manage.py test

    - name: Deploy to Render (pre-prod)
      if: github.ref == 'refs/heads/dev' && success()
      run: |
        # Add your deployment script here
        echo "Deploying to Render for pre-prod branch"

    - name: Create Pull Request to Pre-Prod
      if: github.ref == 'refs/heads/dev' && success()
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Merge dev to pre-prod
        branch: dev
        base: pre-prod
        title: 'Merge dev to pre-prod'
        body: 'This is an automated pull request to merge changes from dev to pre-prod.'

    - name: Deploy to Render (main)
      if: github.ref == 'refs/heads/pre-prod' && success()
      run: |
        # Add your deployment script here
        echo "Deploying to Render for main branch"

    - name: Create Pull Request to Main
      if: github.ref == 'refs/heads/pre-prod' && success()
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Merge pre-prod to main
        branch: pre-prod
        base: main
        title: 'Merge pre-prod to main'
        body: 'This is an automated pull request to merge changes from pre-prod to main.'