name: Deploy Pipeline

on:
  workflow_run:
    workflows: ["Test and Lint"]
    types:
      - completed
  push:  # Temporary trigger for troubleshooting
    branches: ["dev"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Deploy to Pre-Prod
      if: github.ref == 'refs/heads/dev'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git checkout pre-prod
        git merge dev --no-ff -m "Merging changes from dev to pre-prod"
        git push origin pre-prod

    - name: Deploy to Main
      if: github.ref == 'refs/heads/pre-prod'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git checkout main
        git merge pre-prod --no-ff -m "Merging changes from pre-prod to main"
        git push origin main
