name: Deploy Pipeline

on:
  workflow_run:
    workflows: ["Test and Lint"]
    types:
      - completed
  push:  # Temporary trigger for testing
    branches: ["dev"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Fetch All Branches
      run: |
        git fetch origin +refs/heads/*:refs/remotes/origin/*

    - name: Checkout and Update Pre-Prod
      if: github.ref == 'refs/heads/dev'
      env:
        PAT: ${{ secrets.PAT }}  # Use the PAT here
      run: |
        # Create or switch to pre-prod branch
        git checkout -B pre-prod origin/pre-prod
        git merge dev --no-ff --allow-unrelated-histories -s recursive -X theirs -m "Merging changes from dev to pre-prod"
        git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}
        git push origin pre-prod

    - name: Deploy to Main
      if: github.ref == 'refs/heads/pre-prod'
      env:
        PAT: ${{ secrets.PAT }}  # Use the PAT here
      run: |
        # Create or switch to main branch
        git checkout -B main origin/main
        git merge pre-prod --no-ff --allow-unrelated-histories -s recursive -X theirs -m "Merging changes from pre-prod to main"
        git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}
        git push origin main
