name: CI/CD Deployment Pipeline

on:
  push:
    branches:
      - dev

jobs:
  test-and-validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Unit Tests
      run: |
        python manage.py test core.tests

  deploy-to-pre-prod:
    runs-on: ubuntu-latest
    needs: test-and-validate  # This job depends on the 'test-and-validate' job

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Deploy to Pre-Prod
      run: echo "Deploying to Pre-Prod environment"

  deploy-to-main:
    runs-on: ubuntu-latest
    needs: deploy-to-pre-prod  # This job depends on the 'deploy-to-pre-prod' job

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Deploy to Main
      run: echo "Deploying to Main environment"