name: CI/CD Deployment Pipeline

on:
  workflow_run:
    workflows: ["Test and Validate"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Echo Success
      run: echo "Test and Validate workflow completed successfully!"