name: CI/CD Deployment Pipeline

on:
  push:
    branches:
      - dev
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  test-and-validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Unit Tests
      run: |
        python manage.py test core.tests

  deploy-to-pre-prod:
    runs-on: ubuntu-latest
    needs: test-and-validate  # This job depends on the 'test-and-validate' job

    steps:
    - uses: actions/checkout@v4
    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    - name: Fetch All Branches
      run: |
        git fetch origin +refs/heads/*:refs/remotes/origin/*
    - name: Merge Dev into Pre-Prod
      run: |
        git checkout pre-prod
        git merge dev --no-ff -m "Merging changes from dev to pre-prod"
    - name: Push to Pre-Prod
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin pre-prod

  create-pr-to-main:
    runs-on: ubuntu-latest
    needs: deploy-to-pre-prod  # This job depends on the 'deploy-to-pre-prod' job

    steps:
    - name: Create Pull Request to Main
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Merge pre-prod to main
        branch: pre-prod
        base: main
        title: 'Merge pre-prod to main'
        body: 'This is an automated pull request to merge changes from pre-prod to main.'

  deploy-to-main:
    runs-on: ubuntu-latest
    needs: create-pr-to-main  # This job depends on the 'create-pr-to-main' job

    steps:
    - uses: actions/checkout@v4
    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    - name: Fetch All Branches
      run: |
        git fetch origin +refs/heads/*:refs/remotes/origin/*
    - name: Merge Pre-Prod into Main
      run: |
        git checkout main
        git merge pre-prod --no-ff -m "Merging changes from pre-prod to main"
    - name: Push to Main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin main