# .github/workflows/release.yml
name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Run Release-Please
      uses: google-github-actions/release-please-action@v2
      with:
        release-type: simple