name: Test and Lint

on: [push]

jobs:
  test-and-lint:
    name: Run Tests, Linting, and Static Analysis
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 bandit  # Install linting and static analysis tools

    - name: Lint Code
      run: |
        flake8 .  # Lint the code to catch style issues and syntax errors

    - name: Run Unit Tests
      run: |
        python manage.py test core.tests

    - name: Static Analysis
      run: |
        bandit -r .  # Run static analysis to catch security issues