name: Test and Lint

on:
  push:
    branches: [ "dev", "pre-prod", "main" ]

jobs:
  test-and-lint:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

# add linting step here
# add static analysis step here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Unit Tests
      run: |
        python manage.py test core.tests
